services:
  espejismo-remote:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    command: ["--config", "/etc/espejismo/espejismo.toml"]
    ports:
      - "6690:6690/tcp"
    volumes:
      - ../../configs/examples/espejismo.toml:/etc/espejismo/espejismo.toml:ro
    restart: unless-stopped
