[package]
name = "espejismo-client"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[lints]
workspace = true

[[bin]]
name = "espejismo-local"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
espejismo-core = { path = "../espejismo-core" }
futures.workspace = true
netstack-smoltcp.workspace = true
tokio.workspace = true
tracing.workspace = true
tun-rs.workspace = true
